import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar/navbar";
import NavbarBlack from "./component/navbar/navbarBlack";
import Footer from "./component/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarBlack />
        <Navbar />
        <div>{children} </div>
        <Footer />
      </body>
    </html>
  );
}
