name: Deploy Project

on:
  push:
    branches:
      - develop

jobs:
  deploy_front:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Ensure SSH directory exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Dependencies of Front
        working-directory: ./
        run: npm i

      - name: Build Front
        working-directory: ./
        run: npm run build

      - name: Copy Files to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            rm -rf /var/www/front
            mkdir /var/www/front
            cd /var/www/front'
          rsync -avz -e "ssh" ./out/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front
          rsync -avz -e "ssh" ./src/img ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front/
      - name: Restart Nginx
        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo service nginx restart'
