name: Deploy React to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy_front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Ensure SSH directory exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Dependencies of Front
        # 올바른 디렉토리를 설정하세요
        working-directory: ./client # package.json이 있는 디렉토리로 변경
        run: npm install

      - name: Build Front
        working-directory: ./client # 동일한 디렉토리
        run: npm run build

      - name: Copy Files to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            sudo rm -rf /var/www/html
            sudo mkdir /var/www/html
            sudo chown -R $USER:$USER /var/www/html'
          rsync -avz -e "ssh" ./client/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html
